modLoader="javafml" #mandatory
loaderVersion="[36]" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/sxmurxy2007/CustomHitboxes/issues" #optional
[[mods]] #mandatory
modId="customhitboxes" #mandatory
version="1.0" #mandatory
displayName="Custom Hitboxes" #mandatory
displayURL="https://github.com/sxmurxy2007/CustomHitboxes"
logoFile="logo.png" #optional
authors="sxmurxy" #optional
description='''    Customize entities hitboxes with a simple GUI.'''
